name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        # One Go version to start, may test others later to track down the bug
        go-version: [1.24.1]
        # amd64 + arm64 (Linux only)
        runner-arch: [ubuntu-24.04, ubuntu-24.04-arm]
        # arm64 + amd64 (Linux only)
        build-arch: [amd64, arm64]
        # Inside and outside of Docker
        # Introduce Docker later if needed for repro
        #docker: [true, false]
    runs-on: ${{ matrix.runner-arch }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Clone the fluent-bit-go-redis-output repository
        uses: actions/checkout@v4
        with:
          repository: ZigZagT/fluent-bit-go-redis-output
          ref: cd1cd84e11091c76b55a89765ce6dacc35af4f84

      - name: Build ${{ matrix.build-arch }} binary on ${{ matrix.runner-arch }}
      # Runner (Docker: ${{ matrix.docker }})
        run: |
          GOOS=linux GOARCH=${{ matrix.build-arch }} make
