name: Build

on:
  push:

jobs:
  build:
    strategy:
      # Run all jobs to a conclusion to see the outcomes
      fail-fast: false
      matrix:
        # One Go version to start, may test others later to track down the bug
        go-version: [1.24.1]
        # amd64 + arm64 (Linux only)
        runner-arch: [ubuntu-24.04, ubuntu-24.04-arm]
        # arm64 + amd64 (Linux only)
        build-arch: [amd64, arm64]
        # Inside and outside of Docker
        # Introduce Docker later if needed for repro
        docker: ['docker', 'no_docker']
    runs-on: ${{ matrix.runner-arch }}
    steps:
      - name: Clone the fluent-bit-go-redis-output repository
        uses: actions/checkout@v4
        with:
          repository: ZigZagT/fluent-bit-go-redis-output
          ref: cd1cd84e11091c76b55a89765ce6dacc35af4f84

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: install aarch64-linux-gnu-gcc and set CC (for outside Docker only)
        if: matrix.docker == 'no_docker'
        run: |
          apt install -y gcc-aarch64-linux-gnu
          echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Build ${{ matrix.build-arch }} binary on ${{ matrix.runner-arch }} Runner (outside Docker)
        if: matrix.docker == 'no_docker'
        run: |
          make
          file out_redis.so
        env:
          GOOS: linux
          GOARCH: ${{ matrix.build-arch }}
          CGO_ENABLED: 1

      - name: Set up Docker Buildx
        if: matrix.docker == 'docker'
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.build-arch }} binary on ${{ matrix.runner-arch }} Runner (in Docker)
        if: matrix.docker == 'docker'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          build-args: |
            GO_VERSION=${{ matrix.go-version }}
            REPO_GH_USER=ZigZagT
            REPO_NAME=fluent-bit-go-redis-output
            REPO_REF=cd1cd84e11091c76b55a89765ce6dacc35af4f84
          push: false
          provenance: false
          platforms: linux/${{ matrix.build-arch }}
